apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlshortener-deployment
spec:
  selector:
    matchLabels:
      app: urlshortener
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: urlshortener
    spec:
      containers:
        - name: urlshortener
          image: dorianneto/url-shortener-app:latest
          ports:
            - containerPort: 8080
