# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: build

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Display Go version
        run: go version

      - name: Debug
        run: |
          pwd
          echo ${HOME}
          echo ${GITHUB_WORKSPACE}
          echo ${GOPATH}
          echo ${GOROOT}
          ls -al ${GOPATH}

      - name: Install dependencies
        run: |
          go get -u ./...
          go mod tidy

      - name: Test
        run: go test -v ./...

      - name: Build
        run: |
          GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" -o ./bin/app-amd64.exe ./cmd/api/main.go
          GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o ./bin/app-amd64-linux ./cmd/api/main.go
          GOOS=darwin GOARCH=arm64 go build -ldflags "-s -w" -o ./bin/app-amd64-darwin ./cmd/api/main.go

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            ./bin/app-amd64.exe
            ./bin/app-amd64-linux
            ./bin/app-amd64-darwin
            LICENSE.txt
