name: "tagged-release"

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    uses: dorianneto/url-shortener/.github/workflows/build.yml@main
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    needs: build
    permissions:
      contents: write

    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.txt
            bin/app-amd64.exe
            bin/app-amd64-linux
            bin/app-amd64-darwin
